---
- name: Catalyst Switch Commands
  hosts: Catalyst
  gather_facts: no
  
  vars_files:
    -credentials.yml

  vars: 
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: ios
  
    

  tasks:
  - name: show ip int brief 
    ansible.netcommon.cli_command:
      command: show ip int brief
    register: out

  - debug: msg="{{out.stdout}}"
      
