---
- name: Catalyst Switch Commands
  hosts: Catalyst

  tasks:
  - name: Show Version
    ansible.netcommon.cli_command:
      command: show ip int brief
    register: out

  - debug: msg="{{out.stdout}}"
      
