---
- name: Catalyst Switch Commands
  hosts: Catalyst

  vars_files:
  -credentials.yml

  vars: 
    provider:
       user: '{{ cisco_username }}'
       password: '{{ cisco_password }}' 
       validate_certs: no 

  tasks:
  - name: Show Version
    ansible.netcommon.cli_command:
      command: show ip int brief
    register: out

  - debug: msg="{{out.stdout}}"
      
