---
- name: Catalyst Switch Commands
  hosts: Catalyst
  gather_facts: no
  
  vars_files:
    -credentials.yml

  vars: 
    provider:
      ansible_ssh_user: '{{ cisco_username }}'
      ansible_ssh_pass: '{{ cisco_password }}' 
      ansible_connection: ansible.netcommon.network_cli
      ansible_become: yes
      ansible_become_method: enable 

  tasks:
  - name: Show Version
    ansible.netcommon.cli_command:
      command: show ip int brief
    register: out

  - debug: msg="{{out.stdout}}"
      
