---
- name: Run show ip interface brief
  cisco.ios.ios_facts:
    gather_subset: all
  

- name: print the relevant fact we gathered in previous task
  debug:
    msg: "{{ ansible_net_all_ipv4_addresses }}"

  
